Vinh test coverage
hellomentorplus/hatspace pull request #11
Opened 2022-09-07 13:52 UTC by dlvinh

Test coverage on Login Screen

2022-09-07 13:53 UTC, dlvinh commented
![image](https://user-images.githubusercontent.com/85751505/188895773-a9c59ab6-9c79-4e6e-8974-ab35756213b4.png)

2022-09-07 17:18 UTC, suesitran requested changes
Just a few comments

2022-09-07 17:18 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                          TextSpan(children: [
Great choice of widget use

2022-09-07 17:18 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                            backgroundColor: !_isButtonDisable
You can use MaterialStateProperty.resolveWith()

Reference: https://api.flutter.dev/flutter/material/MaterialStateProperty-class.html

How to use:
- remove bool condition to check button state
- use MaterialStateProperty.resolveWith() to switch colour between different states
- button is disabled when onPressed is null

2022-09-07 17:18 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                                ? MaterialStateProperty.all<Color>(
ElevatedButtonTheme is already defined in ThemeData, you don't need to override it here unless you wanna use different theme

2022-09-07 17:18 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                            style: TextStyle(color: Colors.black, fontSize: 20),
TextStyle fit elevated button can be set in ElevatedButtonTheme

2022-09-09 09:50 UTC, suesitran requested changes
please check comments

2022-09-09 09:50 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +            const Size.fromHeight(45),
`Size` with fixed height is not recommended around `Text`

2022-09-09 09:50 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +            ))),
use this `MaterialStateProperty` to set different color for different button state

2022-09-09 09:50 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                          fontWeight: FontWeight.bold),
use `Theme.of(context).textTheme.headline2`, either healine2 or 1, need to check the size.

2022-09-09 09:50 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                      ),
same as above

2022-09-09 09:50 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                              borderRadius:
good!

2022-09-09 09:50 UTC, suesitran commented on lib/Screen/HomeScreen.dart
> +                          },
_isButtonDisable ? null : () {}

2022-09-09 09:50 UTC, suesitran commented on pubspec.yaml
> +  test_coverage: ^0.4.2
good!

2022-09-09 09:50 UTC, suesitran commented on test/widget_test/homescreen_test.dart
> +void homeScreenTest() {
void main() {}

2022-09-10 14:59 UTC, dlvinh commented
![image](https://user-images.githubusercontent.com/85751505/189489081-0a007e06-58f4-4e1e-ac25-d084f646a598.png)

2022-12-12 13:35 UTC, closed without merging