Hs 400] save inspection data
hellomentorplus/hatspace pull request #230
Opened 2024-03-31 06:56 UTC by dlvinh

2024-04-10 19:28 UTC, suesitran requested changes
a few comments

2024-04-14 13:37 UTC, dlvinh commented on lib/data/inspection.dart
> +  String? inspectionId;
already update final

2024-04-16 09:22 UTC, suesitran approved these changes

2024-04-16 09:42 UTC, dlvinh commented on lib/data/inspection.dart
> +  final String? inspectionId;
Yayyy

2024-04-16 11:45 UTC, merged