Hs 55 choose the role screen UI
hellomentorplus/hatspace pull request #25
Opened 2022-12-06 09:03 UTC by asoi1990

2022-12-13 10:15 UTC, hellomentorplus requested changes

2023-02-12 06:24 UTC, suesitran commented
@asoi1990 please merge from dev and try again

2023-02-13 10:50 UTC, suesitran reviewed
Please fix my comments above

2023-02-13 10:50 UTC, suesitran commented on lib/features/sign_up/view/choosing_roles_view.dart
> +              semanticsLabel: 'Linear progress indicator',
I think we missed accessibility requirements in the story, thanks for adding it, but please move it to localisation

2023-02-13 10:50 UTC, suesitran commented on lib/features/sign_up/view/choosing_roles_view.dart
> +                      HatSpaceStrings.of(context).chooseUserRole.toString(),
U don't need to use toString() here

2023-02-13 10:50 UTC, suesitran commented on lib/features/sign_up/view/choosing_roles_view.dart
> +                            .toString(),
U don't need to use toString() here

2023-02-13 10:50 UTC, suesitran commented on lib/features/sign_up/view/choosing_roles_view.dart
> +                  label: HatSpaceStrings.of(context).continueBtn.toString(),
U don't need to use toString() here

2023-02-13 10:50 UTC, suesitran commented on lib/features/sign_up/view/choosing_roles_view.dart
> +                    label: HatSpaceStrings.of(context).cancelBtn.toString(),
U don't need to use toString() here

2023-02-17 09:01 UTC, suesitran approved these changes

2023-02-17 09:01 UTC, hellomentorplus approved these changes

2023-02-17 09:02 UTC, merged