Hs 35 logic account registration google success
hellomentorplus/hatspace pull request #33
Opened 2023-03-02 10:13 UTC by asoi1990

2023-03-03 09:08 UTC, hellomentorplus requested changes

2023-03-03 09:08 UTC, hellomentorplus commented on lib/features/sign_up/view_model/sign_up_bloc.dart
> +        emit(SignUpFailed(SignUpStatusMessage.authenticationFaildMessage));
belong to HS-50, but should not show hard coded text this way. Please use l10n

2023-03-03 09:08 UTC, hellomentorplus commented on lib/models/authentication/authentication_service.dart
> +        email: firebaseUser.displayName);
need email

2023-03-07 09:06 UTC, hellomentorplus requested changes

2023-03-07 09:06 UTC, hellomentorplus commented on lib/features/sign_up/view_model/sign_up_event.dart
> +  // TODO: implement props
if it's not your TODO, just delete it

2023-03-07 09:06 UTC, hellomentorplus commented on lib/models/authentication/authentication_service.dart
> +    if (firebaseUser == null) {
define our own Exception and throw our own exception here

2023-03-10 09:13 UTC, hellomentorplus requested changes

2023-03-10 09:13 UTC, hellomentorplus commented on lib/features/sign_up/view_model/sign_up_bloc.dart
> +    on<SignUpWithGoolge>((event, emit) async {
SignUpWithGoogle

2023-03-10 09:13 UTC, hellomentorplus commented on lib/features/sign_up/view_model/sign_up_state.dart
> +  String errorCode;
all fields in State class need to be `final`

2023-03-10 09:13 UTC, hellomentorplus commented on lib/models/authentication/authentication_service.dart
> +  static const alreadyHaveAccount = SignUpMessageType.AlreadyHaveAccount;
do not translate enum to string.

2023-03-10 09:13 UTC, hellomentorplus commented on lib/l10n/intl_en.arb
> +  "AlreadyHaveAccount":"Already have account",
if it's not required in story, do not create new strings

2023-03-16 15:21 UTC, hellomentorplus approved these changes

2023-03-17 00:31 UTC, suesitran approved these changes

2023-03-17 00:31 UTC, merged