[Hs58] properties database
hellomentorplus/hatspace pull request #57
Opened 2023-05-11 11:16 UTC by dlvinh

2023-05-14 03:54 UTC, suesitran requested changes
Some comments

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +      values.firstWhere((element) => element.name == name);
firstWhere should have orElse to assign default value when no matches value found, to avoid app crash

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +  nsw('New South Wales'),
Please move the strings into 
l10n, you can still access these strings from l10n using .current in the String object

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +      values.firstWhere((element) {
Add orElse to firstWhere

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +      values.firstWhere((element) => element.name == stateName.toLowerCase());
Add orElse to firstWhere

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +      values.firstWhere((element) {
Add orElse to firstWhere

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +      values.firstWhere((element) => element.name == name.toLowerCase());
Add orElse to firstWhere

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +      values.firstWhere((element) => element.name == name.toLowerCase());
Add orElse to firstWhere

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
>        values.firstWhere((element) => element.name == name);
Add orElse to firstWhere

2023-05-14 03:54 UTC, suesitran commented on lib/data/data.dart
> +    this.unitNo = "",
unitNo is nullable, u don't need to assign value to it. Just let it be null

2023-05-14 03:54 UTC, suesitran commented on lib/features/sign_up/view_model/sign_up_bloc.dart
> +      // _storageService.property.getProperty("sCHhTzDvaPgISSsOKHHM");
Please remove this line

2023-05-14 03:54 UTC, suesitran commented on lib/models/storage/member_service/property_storage_service.dart
> +        .get(const GetOptions(source: Source.server));
Using Source.server will not work when device does not have internet connection. We'll need to handle how app behaves when user does not have internet connection. Let's talk to PO about this.

2023-05-14 03:54 UTC, suesitran commented on lib/models/storage/member_service/property_storage_service.dart
> +        .limit(limitQuery)
Does it continue to get the next 20 when we call it the second time?

2023-05-14 03:54 UTC, suesitran commented on lib/models/storage/member_service/property_storage_service.dart
> +        .doc()
This will create new document for this property. We may need a way to update property if the key exists.

2023-06-02 10:40 UTC, suesitran approved these changes

2023-06-04 23:34 UTC, hellomentorplus approved these changes

2023-06-04 23:37 UTC, suesitran approved these changes

2023-06-04 23:37 UTC, merged