Hs106 bottom sheet state and rent period
hellomentorplus/hatspace pull request #77
Opened 2023-06-12 00:06 UTC by dlvinh

2023-06-24 04:42 UTC, suesitran requested changes

2023-06-24 04:42 UTC, suesitran commented on lib/features/add_property_info/view/add_property_minimum_rent_view.dart
> +  final ValueNotifier<MinimumRentPeriod> selectPeriod =
Where do you update value for this ValueNotifer?

2023-06-24 04:42 UTC, suesitran commented on lib/features/add_property/view/add_property_view.dart
> +        BlocProvider<PropertyInforCubit>(
Why do you still need this cubit of we go with my suggestion?

2023-06-26 13:35 UTC, suesitran commented on lib/theme/widgets/hs_modal_view.dart
> +  final ValueChanged onSave;
```suggestion
  final ValueChanged<T> onSave;
```

2023-06-26 13:35 UTC, suesitran commented on lib/theme/widgets/hs_modal_view.dart
> +                      const Expanded(child: SizedBox.shrink()),
why is there an empty `Expanded` here?

2023-06-26 13:35 UTC, suesitran commented on lib/theme/widgets/hs_modal_view.dart
> +                      Expanded(
why does this need to be `Expanded`?

2023-06-27 13:49 UTC, hophongit98 commented on test/theme/hs_modal_selection_view_test.dart
> +    expect(find.byType(SizedBox), findsWidgets);
assert label, assert size of listItem, assert action tap in one item

2023-06-28 13:38 UTC, hophongit98 commented on lib/features/add_property/view/widgets/add_property_info_view/add_property_minimum_rent_view.dart
> +            label: HatSpaceStrings.of(context).minimumRentPeriod,
```suggestion
            label: HatSpaceStrings.current.minimumRentPeriod,
```

2023-06-28 13:38 UTC, hophongit98 commented on test/features/add_property/view/property_info_form_test.dart
> +        'Given when user tap on select state button, then show the  HsModalView with AustraliaState',
```suggestion
        'Given when user taps on select state button, then shows the HsModalView with AustraliaState',
```

2023-06-28 13:38 UTC, hophongit98 commented on test/features/add_property/view/property_info_form_test.dart
> +        'Given when user tap on select minimum button, then show the  HsModalView with Minimum Rent Period',
```suggestion
        'Given when user taps on select minimum button, then shows the HsModalView with Minimum Rent Period',
```

2023-06-28 13:38 UTC, hophongit98 commented on lib/theme/widgets/hs_modal_selection_view.dart
> +      HatSpaceLabel(label: label, isRequired: isRequired ?? false),
We're using prefix is Hs, how about HatSpaceLabel -> HsLabel?

2023-06-28 13:38 UTC, hophongit98 commented on lib/theme/widgets/hs_modal_selection_view.dart
> +            return HatSpaceDropDownButton(
same here: HatSpaceDropDownButton -> HsDropDownButton

2023-06-28 13:38 UTC, hophongit98 commented on test/theme/hs_modal_selection_view_test.dart
> +    }
we can skip these code because it's covered in hs_modal_view
```suggestion
```

2023-06-28 13:38 UTC, hophongit98 commented on test/theme/hs_modal_selection_view_test.dart
> +    expect(find.svgPictureWithAssets(Assets.images.closeIcon), findsOneWidget);
same here, it's belong to hs_modal_view
```suggestion
```

2023-06-28 15:18 UTC, hophongit98 commented on test/features/add_property/view/property_info_form_test.dart
> +        }
You can remove these code

2023-06-28 15:18 UTC, hophongit98 commented on test/features/add_property/view/property_info_form_test.dart
> +        }
same here

2023-06-29 10:21 UTC, hophongit98 approved these changes
LGTM

2023-06-29 10:35 UTC, suesitran commented on lib/features/add_property/view/widgets/add_property_info_view/add_property_price_view.dart
> +        HsLabel(label: HatSpaceStrings.of(context).price, isRequired: true),
`current `

2023-06-29 10:35 UTC, suesitran commented on lib/features/add_property/view/widgets/add_property_info_view/add_property_minimum_rent_view.dart
> +    return BlocListener<AddPropertyCubit, AddPropertyState>(
remove bloc

2023-06-29 10:35 UTC, suesitran commented on lib/features/add_property/view/widgets/add_property_info_view/add_property_state_view.dart
> +    return BlocListener<AddPropertyCubit, AddPropertyState>(
remove bloc

2023-06-29 10:35 UTC, suesitran commented on lib/features/add_property/view_model/add_property_state.dart
> +
remove states

2023-06-29 11:38 UTC, suesitran approved these changes

2023-06-29 12:17 UTC, merged