HS-81 redesigned SignUp Screen
hellomentorplus/hatspace pull request #83
Opened 2023-06-22 10:51 UTC by Khaxtran

added background image
added app logo
updated buttons UI
updated skip button

2023-06-22 14:55 UTC, hophongit98 commented on lib/features/sign_up/view/sign_up_view.dart
> +                              const EdgeInsets.fromLTRB(24.0, 16.0, 24.0, 16.0),
pls using HsDimens

2023-06-22 14:55 UTC, hophongit98 commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
same here

2023-06-22 14:55 UTC, hophongit98 commented on lib/features/sign_up/view/sign_up_view.dart
> +                          padding: const EdgeInsets.symmetric(horizontal: 24.0),
same here

2023-06-22 14:56 UTC, hophongit98 reviewed
SafeArea(
                child: Column(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      TextOnlyButton(
                        label: HatSpaceStrings.current.skip,
                        onPressed: () {
                          context
                              .read<SignUpBloc>()
                              .add(const CloseSignUpScreen());
                        },
                        style: ButtonStyle(
                          foregroundColor: MaterialStateProperty.all<Color>(
                            colorScheme.onPrimary,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(
                    height: HsDimens.spacing150,
                  ),
                  ExcludeSemantics(
                    child: SvgPicture.asset(
                      Assets.images.logo,
                      width: HsDimens.size118,
                      height: HsDimens.size64,
                    ),
                  ),
                  const SizedBox(
                    height: HsDimens.spacing80,
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(
                        horizontal: HsDimens.spacing24),
                    child: SecondaryButton(
                      contentAlignment: MainAxisAlignment.start,
                      label: HatSpaceStrings.of(context).emailSignUp,
                      iconUrl: Assets.icons.envelope,
                      overrideIconColor: false,
                      style: ButtonStyle(
                        backgroundColor:
                            MaterialStateProperty.all<Color>(Colors.white),
                        padding: MaterialStateProperty.all<EdgeInsetsGeometry>(
                            const EdgeInsets.all(16.0)),
                      ),
                      onPressed: () {},
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(
                        horizontal: HsDimens.spacing24,
                        vertical: HsDimens.spacing16),
                    child: SecondaryButton(
                      contentAlignment: MainAxisAlignment.start,
                      label: HatSpaceStrings.of(context).facebookSignUp,
                      iconUrl: Assets.icons.facebook,
                      overrideIconColor: false,
                      style: ButtonStyle(
                        backgroundColor:
                            MaterialStateProperty.all<Color>(Colors.white),
                        padding: MaterialStateProperty.all<EdgeInsetsGeometry>(
                            const EdgeInsets.all(16.0)),
                      ),
                      onPressed: () {
                        context
                            .read<SignUpBloc>()
                            .add(const SignUpWithFacebook());
                      },
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 24.0),
                    child: SecondaryButton(
                      contentAlignment: MainAxisAlignment.start,
                      label: HatSpaceStrings.of(context).googleSignUp,
                      iconUrl: Assets.icons.google,
                      overrideIconColor: false,
                      style: ButtonStyle(
                        backgroundColor:
                            MaterialStateProperty.all<Color>(Colors.white),
                        padding: MaterialStateProperty.all<EdgeInsetsGeometry>(
                            const EdgeInsets.all(16.0)),
                      ),
                      onPressed: () {
                        context
                            .read<SignUpBloc>()
                            .add(const SignUpWithGoogle());
                      },
                    ),
                  )
                ]))

2023-06-23 00:51 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                    crossAxisAlignment: CrossAxisAlignment.end,
Yes, line 70 is unnecessary, will remove it

2023-06-23 00:59 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                    child: Column(
The idea was to use a root Column that contains 2 nested columns, using space-between alignment to separate the skip button + logo (top column) and sign-in buttons (bottom column).

2023-06-23 01:03 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                child: Column(
@suesitran what's your thought on this?

2023-06-23 01:37 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
Done

2023-06-23 01:37 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                          padding: const EdgeInsets.symmetric(horizontal: 24.0),
Done

2023-06-23 01:37 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
Done

2023-06-23 01:38 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                              const EdgeInsets.fromLTRB(24.0, 16.0, 24.0, 16.0),
Done

2023-06-23 01:38 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
Done

2023-06-23 01:38 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                          padding: const EdgeInsets.symmetric(horizontal: 24.0),
Done

2023-06-23 01:38 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +                              child: SvgPicture.asset(Assets.images.logo),
Done

2023-06-23 03:15 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                    child: Column(
This is to ensure the screen scale relatively to different device screen size

2023-06-23 03:16 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                child: Column(
explanation above

2023-06-23 04:55 UTC, hellomentorplus requested changes

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                          padding: const EdgeInsets.symmetric(horizontal: 24.0),
not done, please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                            padding: const EdgeInsets.only(bottom: 80.0),
please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                              child: SvgPicture.asset(Assets.images.logo),
please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                              const EdgeInsets.fromLTRB(24.0, 16.0, 24.0, 16.0),
please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                          padding: const EdgeInsets.symmetric(horizontal: 24.0),
please fix @Khaxtran

2023-06-23 04:55 UTC, hellomentorplus commented on lib/features/sign_up/view/sign_up_view.dart
> +                                      const EdgeInsets.all(16.0)),
please fix @Khaxtran

2023-06-23 05:36 UTC, hophongit98 commented on lib/features/sign_up/view/sign_up_view.dart
> +                            child: SizedBox(
Remove SizedBox here because SvgPicture widget already has the width and height properties

2023-06-23 05:39 UTC, hophongit98 commented on lib/l10n/intl_en.arb
> +  "skip": "Skip,
```suggestion
  "skip": "Skip",
```

2023-06-23 05:39 UTC, hophongit98 commented on lib/strings/intl/messages_en.dart
> +        "skip": MessageLookupByLibrary.simpleMessage("SKIP"),
This change should be reverted, right?

2023-06-23 05:39 UTC, hophongit98 commented on lib/strings/intl/messages_en.dart
> +        "skip": MessageLookupByLibrary.simpleMessage("SKIP"),
Look like you have to re-run the generated script again.

2023-06-25 04:03 UTC, hophongit98 reviewed
Run script generating resource and push again, pls

2023-06-26 07:52 UTC, hophongit98 commented on lib/features/sign_up/view/sign_up_view.dart
> +              title: HatSpaceStrings.of(context).signinErrorToastTitle,
@Khaxtran pls update here

2023-06-26 07:52 UTC, hophongit98 commented on lib/features/sign_up/view/sign_up_view.dart
> +              message: HatSpaceStrings.of(context).signinErrorToastMessage);
same here

2023-06-26 07:58 UTC, suesitran submitted a review, later dismissed

2023-06-26 08:51 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +              message: HatSpaceStrings.of(context).signinErrorToastMessage);
it's updated in this commit 342fbe0a5c1b171a54b2e901db527c8576a80228

2023-06-26 08:51 UTC, Khaxtran commented on lib/features/sign_up/view/sign_up_view.dart
> +              title: HatSpaceStrings.of(context).signinErrorToastTitle,
it's updated in this commit 342fbe0a5c1b171a54b2e901db527c8576a80228

2023-06-26 12:07 UTC, hophongit98 submitted a review, later dismissed
Run script generating resource and push again, pls

2023-06-27 01:51 UTC, hophongit98 submitted a review, later dismissed
LGTM

2023-06-27 01:56 UTC, hellomentorplus approved these changes

2023-06-29 11:37 UTC, suesitran approved these changes

2023-06-29 11:44 UTC, merged